root = "."
tmp_dir = "./bin/.air"

[build]
cmd = "commit_sha=$(git rev-parse HEAD 2>/dev/null || printf 'dev'); go build -trimpath -ldflags=\"-X main.commitHash=${commit_sha}\" -o ./bin/lancert ./cmd/lancert"
bin = "./bin/lancert"
full_bin = "env LANCERT_SUSPENDED=true ./bin/lancert"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["bin", "certs", "data", "static"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[screen]
clear_on_rebuild = true
keep_scroll = true
